### ISSUE TITLE
Error building web-app

### ISSUE THREAD

**Issue by andybrown668** [UniconLabs/shibboleth-idp-webapp#2]
hi there,

running 'mvn validate' per the build instructions errors out due to missing dependencies:

`[ERROR] Failed to execute goal on project idp-webapp-overlay: Could not resolve dependencies for project net.unicon.idp:idp-webapp-overlay:war:3.2.0: The following artifacts could not be resolved: net.unicon.idp:idp-webapp:war:3.2.0, net.unicon.idp:idp-webapp-support:jar:3.2.0: Failure to find net.unicon.idp:idp-webapp:war:3.2.0 in https://build.shibboleth.net/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of shib-release has elapsed or updates are forced -> [Help 1]`

I took a quick look at the maven repo, but don't see an idp subfolder under unicon at https://repo.maven.apache.org/maven2/net/unicon/

**Comment by mmoayyed** [comment]
I don't see any refs to validate. Try running package or install instead.

**Comment by mmoayyed** [comment]
The support module is in the repo itself.
