### ISSUE TITLE
Jetty conf files not provided

### ISSUE THREAD

**Issue by nachetecanon** [UniconLabs/shibboleth-idp-webapp#3]
Hi all, it would be very useful to have available the jetty.xml, jetty-ssl.xml, yetty-https.xml, logback.xml files preconfigured. This way could be easy to quickly test via maven validate, the overlay generated.
Thanks in advance and best regards

**Comment by mmoayyed** [comment]
Sure thing. I'll add them.

**Comment by mmoayyed** [comment]
This is done now.
1. Added jetty config
2. Upgraded to 3.2.1
3. Updated instructions and build commands.
